/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

/**
 *
 * @author joao
 */
public class Principal extends javax.swing.JPanel {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnTransferencia = new javax.swing.JButton();
        btnSaque = new javax.swing.JButton();
        btnDepositar = new javax.swing.JButton();
        btnExtrato = new javax.swing.JButton();
        jRadioButton1 = new javax.swing.JRadioButton();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTransferencia.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnTransferencia.setText("Transferencia");
        add(btnTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));

        btnSaque.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSaque.setText("Saque");
        add(btnSaque, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 90, -1));

        btnDepositar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDepositar.setText("Deposito");
        add(btnDepositar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 50, 130, -1));

        btnExtrato.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExtrato.setText("Extrato");
        add(btnExtrato, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 90, -1));

        jRadioButton1.setText("jRadioButton1");
        add(jRadioButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, -1, -1));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExtrato;
    private javax.swing.JButton btnSaque;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
